version: "3.7"

networks:
  monitoring:
    external: true

services:

  quarkus:
    image: kjtully/java-nativeimage-quarkus-restservice:latest
    container_name: quarkus
    environment:
      - OTEL_SERVICE_NAME=java-nativeimage-quarkus-restservice
      - OTEL_SERVICE_NAMESPACE=kjt-java-nativeimage
    #env_file:
      #- otel-chain-env-vars.env
    ports:
      - "8080:8080"
    networks:
      - monitoring
 
