version: "3.7"

networks:
  monitoring:
    external: true

services:

  quarkus:
    image: kjt/quarkus-grpc-otel:1.0.0-SNAPSHOT
    container_name: quarkus
    environment:
      - OTEL_SERVICE_NAME=quarkus-grpc-otel
      - OTEL_SERVICE_NAMESPACE=kjt-quarkus-nativeimage
    #env_file:
      #- otel-chain-env-vars.env
    ports:
      - "8081:8081"
      #- "9009:9009"
    networks:
      - monitoring
 
